<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sandy" failures="0" tests="4" name="test.TestScenario3" time="4.011" errors="1" timestamp="2025-06-09T00:14:55 IST" skipped="0">
  <testcase classname="test.TestScenario3" name="smoke02" time="0.002"/>
  <testcase classname="test.TestScenario3" name="Mobilelogin" time="4.005">
    <error message="Method test.TestScenario01.Mobilelogin() didn&#039;t finish within the time-out 4000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method test.TestScenario01.Mobilelogin() didn't finish within the time-out 4000
at java.base/java.lang.Thread.sleepNanos0(Native Method)
at java.base/java.lang.Thread.sleepNanos(Thread.java:496)
at java.base/java.lang.Thread.sleep(Thread.java:588)
at test.TestScenario01.Mobilelogin(TestScenario01.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </error>
  </testcase> <!-- Mobilelogin -->
  <testcase classname="test.TestScenario3" name="smoke" time="0.002"/>
  <testcase classname="test.TestScenario3" name="main" time="0.002"/>
</testsuite> <!-- test.TestScenario3 -->
